name: test and build docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  main:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
          # image: python:3.12
          image: nikolaik/python-nodejs:python3.12-nodejs24
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test imports
        run: |
          uv sync --link-mode=symlink
          uv pip install pytest
          uv run python -m pytest tests/test_imports.py
      - name: pyright
        run: |
          uv sync --extra all --extra dev --link-mode=symlink
          uv pip install -r requirements/type_checking.txt --no-deps
          uv run python -m pyright -p pyrightconfig.json asr_eval
      - name: tests
        run: |
          uv sync --extra all --extra dev --link-mode=symlink
          uv run python -m pytest tests
      - name: xdoctest
        run: |
          uv sync --extra all --extra dev --link-mode=symlink
          uv pip install git+https://github.com/salute-developers/GigaAM
          uv run python -m xdoctest asr_eval --verbose 1
      # - name: sphinx doctest  # disabled until doctesting fixed
      #   run: |
      #     uv sync --extra all --extra dev --link-mode=symlink
      #     uv pip install git+https://github.com/salute-developers/GigaAM
      #     uv run sphinx-build -M doctest docs/source docs/build docs/source/guide_alignment_wer.rst
      #     uv run sphinx-build -M doctest docs/source docs/build docs/source/guide_streaming_evaluation.rst
      #     uv run sphinx-build -M doctest docs/source docs/build docs/source/guide_evaluation_dashboard.rst
      - name: build docs
        run: |
          uv sync --extra dev --extra dev --link-mode=symlink
          rm -rf docs/build
          uv run sphinx-build docs/source docs/build
          (cd docs && uv run make simplepdf)
      - name: setup pages
        if: ${{ !env.ACT }}
        uses: actions/configure-pages@v5
      - name: upload artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/build'
      - name: deploy to github pages
        if: ${{ !env.ACT }}
        id: deployment
        uses: actions/deploy-pages@v4